# Generated by Django 5.1.6 on 2025-04-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='testing title', max_length=255),
            preserve_default=False,
        ),
    ]
