# Generated by Django 5.1.6 on 2025-05-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_rating_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('hours', models.PositiveIntegerField()),
                ('activities', models.TextField()),
                ('score', models.CharField(max_length=50)),
                ('learnings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='reports/')),
                ('date_and_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('activities_tasks', models.TextField(blank=True, null=True)),
                ('score_accomplished_targets', models.CharField(blank=True, max_length=255, null=True)),
                ('new_learnings', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'week_number')},
            },
        ),
    ]
