# Generated by Django 5.1.6 on 2025-05-08 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_weekreport_weeklyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='intern',
            name='course',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='name',
        ),
        migrations.AddField(
            model_name='intern',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='section',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='activities',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='hours',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='intern',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='project_app.intern'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='learnings',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='score',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='week',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.coordinator'),
        ),
        migrations.CreateModel(
            name='CoordinatorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('assessment', models.TextField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.coordinator')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.intern')),
            ],
        ),
        migrations.CreateModel(
            name='ChairmanAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.chairman')),
                ('coordinator_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.coordinatorassessment')),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='activities_tasks',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='date_and_hours',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='new_learnings',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='report_file',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='score_accomplished_targets',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='student',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='week_number',
        ),
    ]
